spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 889977889977
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      # table-prefix:
  mapper-locations: classpath:mapper/**/*.xml